<?php
/**
 * Plugin Name: OrbyChat Sales AI
 * Plugin URI: https://orby.chat
 * Description: The official OrbyChat companion for WordPress and WooCommerce. Connect your store to your OrbyChat Sales AI agent to enable product-aware chat, abandoned cart recovery, and seamless lead syncing.
 * Version: 1.0.0
 * Author: OrbyChat Team
 * Author URI: https://orby.chat
 * License: GPLv2 or later
 * Text Domain: orbychat-sales-ai
 * Domain Path: /languages
 */

if (!defined('WPINC')) {
    die;
}

class OrbyChat_Sales_AI {

    private $option_name = 'orbychat_sales_ai_settings';

    public function __construct() {
        add_action('admin_menu', array($this, 'add_admin_menu'));
        add_action('admin_init', array($this, 'settings_init'));
        add_action('wp_footer', array($this, 'inject_widget_script'));
        
        // WooCommerce Hooks
        if (class_exists('WooCommerce')) {
            add_action('woocommerce_add_to_cart', array($this, 'track_cart_event'), 10, 6);
            add_action('woocommerce_thankyou', array($this, 'track_order_completed'));
            add_action('woocommerce_cart_updated', array($this, 'track_cart_event'));
            add_action('woocommerce_order_status_completed', array($this, 'track_order_completed'));
        }

        // REST API for OrbyChat
        add_action('rest_api_init', array($this, 'register_rest_routes'));

        // Localized strings for Turkish fallback
        add_filter('gettext', array($this, 'translate_turkish'), 10, 3);
    }

    public function translate_turkish($translated, $text, $domain) {
        if ($domain !== 'orbychat-sales-ai' || !str_starts_with(get_locale(), 'tr')) {
            return $translated;
        }

        $translations = array(
            'WooCommerce is not active on this site.' => 'WooCommerce bu sitede aktif değil.',
            'Generated by OrbyChat Sales AI for a visitor.' => 'OrbyChat Satış Yapay Zekası tarafından bir ziyaretçi için oluşturuldu.',
            'Could not generate a discount code at this time.' => 'Şu anda indirim kodu oluşturulamadı.',
            '%d%% OFF' => '%%%d İNDİRİM',
            'Your exclusive %d%% discount code %s is ready! It is valid for the next 24 hours. Copy it and apply at checkout.' => 'Size özel %%%d indirim kodunuz %s hazır! Önümüzdeki 24 saat boyunca geçerlidir. Kopyalayıp ödeme sayfasında uygulayabilirsiniz.',
            'WooCommerce is not active.' => 'WooCommerce aktif değil.',
            'Order not found.' => 'Sipariş bulunamadı.',
            'Order #%s is currently %s. Total: %s %s. Items: %s' => '#%s numaralı sipariş şu anda %s durumunda. Toplam: %s %s. Ürünler: %s',
            'Connection Settings' => 'Bağlantı Ayarları',
            'OrbyChat API URL' => 'OrbyChat API Adresi',
            'Workspace API Token' => 'Çalışma Alanı API Anahtarı',
            'Agent ID' => 'Asistan Kimliği',
            'Your OrbyChat installation URL (no trailing slash).' => 'OrbyChat kurulum adresiniz (sonunda eğik çizgi olmadan).',
            'Found in your OrbyChat Workspace Settings.' => 'OrbyChat Çalışma Alanı Ayarlarınızda bulunur.',
            'The UUID of the agent you want to embed.' => 'Yerleştirmek istediğiniz asistanın UUID kodu.',
            'Content Sync' => 'İçerik Senkronizasyonu',
            'Sync your WooCommerce products and pages to OrbyChat to make your AI agent aware of your catalog.' => 'Yapay zeka asistanınızın kataloğunuzdan haberdar olması için WooCommerce ürünlerinizi ve sayfalarınızı OrbyChat ile senkronize edin.',
            'Sync Now' => 'Şimdi Senkronize Et',
            'Syncing...' => 'Senkronize ediliyor...',
            'Success!' => 'Başarılı!',
            'items synced.' => 'öğe senkronize edildi.',
            'Error:' => 'Hata:',
            'Network error.' => 'Ağ hatası.',
            'Unauthorized' => 'Yetkisiz erişim',
            'API settings not configured' => 'API ayarları yapılandırılmamış',
            'Failed to sync with OrbyChat.' => 'OrbyChat ile senkronizasyon başarısız oldu.',
            'No phone' => 'Telefon yok',
            'No page' => 'Sayfa yok',
        );

        return isset($translations[$text]) ? $translations[$text] : $translated;
    }

    public function register_rest_routes() {
        register_rest_route('orbychat/v1', '/coupons/apply', array(
            'methods' => 'POST',
            'callback' => array($this, 'rest_apply_coupon'),
            'permission_callback' => array($this, 'validate_api_token'),
        ));

        register_rest_route('orbychat/v1', '/orders/(?P<id>\d+)', array(
            'methods' => 'GET',
            'callback' => array($this, 'rest_get_order'),
            'permission_callback' => array($this, 'validate_api_token'),
        ));
    }

    public function validate_api_token(WP_REST_Request $request) {
        $token = $request->get_header('X-OrbyChat-Token');
        $options = get_option($this->option_name);
        $saved_token = isset($options['api_token']) ? $options['api_token'] : '';
        return !empty($token) && hash_equals($saved_token, $token);
    }

    public function rest_apply_coupon(WP_REST_Request $request) {
        if (!class_exists('WooCommerce')) {
            return new WP_Error('no_wc', __('WooCommerce is not active on this site.', 'orbychat-sales-ai'), array('status' => 400));
        }

        $params = $request->get_json_params();
        $max_discount = isset($params['max_discount']) ? intval($params['max_discount']) : 10;
        
        // Generate a unique, professional coupon code
        $coupon_code = strtoupper('ORBY-' . wp_generate_password(6, false));
        
        try {
            $coupon = new WC_Coupon();
            $coupon->set_code($coupon_code);
            $coupon->set_discount_type('percent');
            $coupon->set_amount($max_discount);
            $coupon->set_individual_use(true);
            $coupon->set_usage_limit(1); // One time use for this visitor
            $coupon->set_description(__('Generated by OrbyChat Sales AI for a visitor.', 'orbychat-sales-ai'));
            $coupon->set_date_expires(date('Y-m-d', strtotime('+24 hours'))); // Valid for 24 hours
            
            $coupon->save();
        } catch (Exception $e) {
            return new WP_Error('coupon_creation_failed', __('Could not generate a discount code at this time.', 'orbychat-sales-ai'), array('status' => 500));
        }
        
        return array(
            'status' => 'success',
            'code' => $coupon_code,
            'discount_text' => str_starts_with(get_locale(), 'tr') 
                ? sprintf('%%%d İNDİRİM', $max_discount)
                : sprintf(__('%d%% OFF', 'orbychat-sales-ai'), $max_discount),
            'instructions' => sprintf(__('Your exclusive %d%% discount code %s is ready! It is valid for the next 24 hours. Copy it and apply at checkout.', 'orbychat-sales-ai'), $max_discount, $coupon_code)
        );
    }

    public function rest_get_order($request) {
        if (!class_exists('WooCommerce')) {
            return new WP_Error('no_wc', __('WooCommerce is not active.', 'orbychat-sales-ai'), array('status' => 400));
        }

        $order = wc_get_order($request['id']);
        if (!$order) {
            return new WP_Error('not_found', __('Order not found.', 'orbychat-sales-ai'), array('status' => 404));
        }

        $items_summary = array();
        foreach ($order->get_items() as $item) {
            $items_summary[] = $item->get_name() . ' (x' . $item->get_quantity() . ')';
        }

        $status_name = wc_get_order_status_name($order->get_status());
        $summary = sprintf(
            __('Order #%s is currently %s. Total: %s %s. Items: %s', 'orbychat-sales-ai'),
            $order->get_order_number(),
            $status_name,
            $order->get_total(),
            $order->get_currency(),
            implode(', ', $items_summary)
        );

        return array(
            'order_id' => $order->get_order_number(),
            'status' => $status_name,
            'total' => $order->get_total(),
            'currency' => $order->get_currency(),
            'payment_method' => $order->get_payment_method_title(),
            'date_created' => $order->get_date_created()->date('Y-m-d H:i:s'),
            'summary' => $summary,
            'tracking_url' => $this->get_tracking_url($order)
        );
    }

    /**
     * Attempts to find a tracking URL if common tracking plugins are used.
     */
    private function get_tracking_url($order) {
        // Support for "WooCommerce Shipment Tracking" plugin
        if (function_exists('wc_st_get_tracking_number')) {
            $tracking = wc_st_get_tracking_number($order->get_id());
            if ($tracking) return $tracking;
        }

        // Support for AfterShip or similar (metadata check)
        $aftership_tracking = $order->get_meta('_aftership_tracking_number');
        if ($aftership_tracking) return 'https://www.aftership.com/track/' . $aftership_tracking;

        return '#';
    }

    public function add_admin_menu() {
        add_menu_page(
            'OrbyChat AI',
            'OrbyChat AI',
            'manage_options',
            'orbychat-sales-ai',
            array($this, 'options_page'),
            'dashicons-superhero'
        );
    }

    public function settings_init() {
        register_setting('orbychatPluginPage', $this->option_name);

        add_settings_section(
            'orbychat_pluginPage_section',
            __('Connection Settings', 'orbychat-sales-ai'),
            null,
            'orbychatPluginPage'
        );

        add_settings_field(
            'api_url',
            __('OrbyChat API URL', 'orbychat-sales-ai'),
            array($this, 'api_url_render'),
            'orbychatPluginPage',
            'orbychat_pluginPage_section'
        );

        add_settings_field(
            'api_token',
            __('Workspace API Token', 'orbychat-sales-ai'),
            array($this, 'api_token_render'),
            'orbychatPluginPage',
            'orbychat_pluginPage_section'
        );

        add_settings_field(
            'agent_id',
            __('Agent ID', 'orbychat-sales-ai'),
            array($this, 'agent_id_render'),
            'orbychatPluginPage',
            'orbychat_pluginPage_section'
        );
    }

    public function api_url_render() {
        $options = get_option($this->option_name);
        ?>
        <input type='text' name='<?php echo $this->option_name; ?>[api_url]' value='<?php echo isset($options['api_url']) ? esc_attr($options['api_url']) : ''; ?>' class='regular-text' placeholder='https://orby.chat'>
        <p class='description'><?php _e('Your OrbyChat installation URL (no trailing slash).', 'orbychat-sales-ai'); ?></p>
        <?php
    }

    public function api_token_render() {
        $options = get_option($this->option_name);
        ?>
        <input type='password' name='<?php echo $this->option_name; ?>[api_token]' value='<?php echo isset($options['api_token']) ? esc_attr($options['api_token']) : ''; ?>' class='regular-text'>
        <p class='description'><?php _e('Found in your OrbyChat Workspace Settings.', 'orbychat-sales-ai'); ?></p>
        <?php
    }

    public function agent_id_render() {
        $options = get_option($this->option_name);
        ?>
        <input type='text' name='<?php echo $this->option_name; ?>[agent_id]' value='<?php echo isset($options['agent_id']) ? esc_attr($options['agent_id']) : ''; ?>' class='regular-text'>
        <p class='description'><?php _e('The UUID of the agent you want to embed.', 'orbychat-sales-ai'); ?></p>
        <?php
    }

    public function options_page() {
        ?>
        <div class="wrap">
            <h1><?php _e('OrbyChat Sales AI', 'orbychat-sales-ai'); ?></h1>
            <form action='options.php' method='post'>
                <?php
                settings_fields('orbychatPluginPage');
                do_settings_sections('orbychatPluginPage');
                submit_button();
                ?>
            </form>

            <hr>

            <h2><?php _e('Content Sync', 'orbychat-sales-ai'); ?></h2>
            <p><?php _e('Sync your WooCommerce products and pages to OrbyChat to make your AI agent aware of your catalog.', 'orbychat-sales-ai'); ?></p>
            <button id="orbychat-sync-now" class="button button-secondary"><?php _e('Sync Now', 'orbychat-sales-ai'); ?></button>
            <div id="orbychat-sync-status" style="margin-top: 10px; font-weight: bold;"></div>

            <script type="text/javascript">
                document.getElementById('orbychat-sync-now').addEventListener('click', function() {
                    const status = document.getElementById('orbychat-sync-status');
                    status.innerText = '<?php _e('Syncing...', 'orbychat-sales-ai'); ?>';
                    this.disabled = true;

                    fetch(ajaxurl, {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: 'action=orbychat_sync_content&_wpnonce=<?php echo wp_create_nonce("orbychat_sync"); ?>'
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            status.style.color = 'green';
                            status.innerText = '<?php _e('Success!', 'orbychat-sales-ai'); ?> ' + data.data.count + ' <?php _e('items synced.', 'orbychat-sales-ai'); ?>';
                        } else {
                            status.style.color = 'red';
                            status.innerText = '<?php _e('Error:', 'orbychat-sales-ai'); ?> ' + data.data;
                        }
                        this.disabled = false;
                    })
                    .catch(error => {
                        status.style.color = 'red';
                        status.innerText = '<?php _e('Network error.', 'orbychat-sales-ai'); ?>';
                        this.disabled = false;
                    });
                });
            </script>
        </div>
        <?php
    }

    public function inject_widget_script() {
        $options = get_option($this->option_name);
        if (empty($options['api_url']) || empty($options['agent_id'])) {
            return;
        }

        $url = rtrim($options['api_url'], '/') . '/widget/widget.js';
        $agent_id = esc_attr($options['agent_id']);

        echo "\n<!-- OrbyChat Sales AI Widget -->\n";
        echo "<script async src='{$url}' data-agent-id='{$agent_id}'></script>\n";
    }

    public function handle_sync_ajax() {
        check_ajax_referer('orbychat_sync');

        if (!current_user_can('manage_options')) {
            wp_send_json_error(__('Unauthorized', 'orbychat-sales-ai'));
        }

        $options = get_option($this->option_name);
        if (empty($options['api_url']) || empty($options['api_token'])) {
            wp_send_json_error(__('API settings not configured', 'orbychat-sales-ai'));
        }

        $items = array();
        
        // 1. Collect Products
        if (class_exists('WooCommerce')) {
            $wc_products = wc_get_products(array('status' => 'publish', 'limit' => -1));
            foreach ($wc_products as $product) {
                $items[] = array(
                    'external_id' => 'wc_' . $product->get_id(),
                    'type' => 'product',
                    'title' => $product->get_name(),
                    'url' => get_permalink($product->get_id()),
                    'body' => strip_tags($product->get_description() . ' ' . $product->get_short_description()),
                    'price' => $product->get_price(),
                    'currency' => get_woocommerce_currency(),
                    'image_url' => wp_get_attachment_url($product->get_image_id()),
                    'in_stock' => $product->is_in_stock(),
                );
            }
        }

        // 2. Collect Pages & Posts
        $posts = get_posts(array('post_type' => array('page', 'post'), 'post_status' => 'publish', 'numberposts' => -1));
        foreach ($posts as $post) {
            $items[] = array(
                'external_id' => 'wp_' . $post->ID,
                'type' => 'page',
                'title' => $post->post_title,
                'url' => get_permalink($post->ID),
                'body' => strip_shortcodes(strip_tags($post->post_content)),
            );
        }

        // 3. Post to OrbyChat
        $response = wp_remote_post(rtrim($options['api_url'], '/') . '/api/v1/integrations/wordpress/sync', array(
            'headers' => array(
                'X-OrbyChat-Token' => $options['api_token'],
                'Content-Type' => 'application/json',
            ),
            'body' => json_encode(array(
                'agent_id' => $options['agent_id'],
                'items' => $items,
            )),
            'timeout' => 60,
        ));

        if (is_wp_error($response)) {
            wp_send_json_error($response->get_error_message());
        }

        $body = json_decode(wp_remote_retrieve_body($response), true);
        if (wp_remote_retrieve_response_code($response) !== 200) {
            wp_send_json_error($body['message'] ?? __('Failed to sync with OrbyChat.', 'orbychat-sales-ai'));
        }

        wp_send_json_success(array('count' => count($items)));
    }

    public function track_cart_event() {
        if (!function_exists('WC') || !WC()->cart) return;

        $cart = WC()->cart;
        $data = array(
            'event' => 'cart_updated',
            'cart_total' => $cart->get_total('raw'),
            'currency' => get_woocommerce_currency(),
            'items' => array()
        );

        foreach ($cart->get_cart() as $item) {
            $data['items'][] = array(
                'id' => $item['product_id'],
                'name' => get_the_title($item['product_id']),
                'quantity' => $item['quantity'],
                'price' => $item['data']->get_price()
            );
        }

        $this->push_to_orbychat('events/cart', $data);
    }

    public function track_order_completed($order_id) {
        $order = wc_get_order($order_id);
        if (!$order) return;

        $data = array(
            'event' => 'order_completed',
            'order_id' => $order_id,
            'total' => $order->get_total(),
            'currency' => $order->get_currency(),
            'email' => $order->get_billing_email()
        );

        $this->push_to_orbychat('events/order', $data);
    }

    private function push_to_orbychat($endpoint, $data) {
        $options = get_option($this->option_name);
        $token = isset($options['api_token']) ? $options['api_token'] : '';
        if (empty($token) || empty($options['api_url'])) return;

        wp_remote_post(rtrim($options['api_url'], '/') . '/api/v1/integrations/wordpress/' . $endpoint, array(
            'headers' => array(
                'X-OrbyChat-Token' => $token,
                'Content-Type'     => 'application/json',
            ),
            'body' => json_encode($data),
            'blocking' => false,
        ));
    }
}

add_action('wp_ajax_orbychat_sync_content', array(new OrbyChat_Sales_AI(), 'handle_sync_ajax'));
new OrbyChat_Sales_AI();
